---
project: project_name
method: [mast, deseq2]
metadata: ./data/metadata.csv
expression_data: ./data/counts.csv
output_dir: /home/ciro/large/tests/dgea
# group_up,group_down,test_column,name,context,filters
comparisons:
  file: /home/ciro/scripts/dgea/data/comparisons.csv
  c1:
    test_column: test_column
    contrast: [group_up, group_down]
    filters: {column_filter: [G1, G2], feat_IL5_1: IL5p}
    name: NAME1vsNAME2 # this is able to rename group_up and group_down
    context: context1 # used for a set of comparisons, e.g., clusters, disease, etc.
    job: {walltime: 03:00:00, mem: 15gb, ppn: 1, nodes: 1}
  c2:
    test_column: RNA_snn_res.0.2
    contrast: [0, 1, 2]
    filters: {column_filter: [G1, G2]}
    context: clusters
covariates: none
down_sample: FALSE
padj_threshold: 0.05
fc_threshold: 0.25
# counts transformations: log2cpm, log2, cpm; file.csv~log2
# Also used for visualisations
ctrans: log2cpm
colours: ./data/colours_df.csv
job:
  template: https://raw.githubusercontent.com/vijaybioinfo/cellranger_wrappeR/main/routine_template.sh
  main: {walltime: 07:00:00, mem: 16gb, ppn: 1, nodes: 1}
  depend: none
  submit: no # yes, no
exec: Rscript
script: /home/ciro/scripts/dgea/R/dgea.R
...

# You can specify that two columns will be pasted with '~', then you need to
# refer to the new groups separated by '_': column1~column2 and group1_group2
